CREATE TABLE [GalleryImages] (
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [ImageUrl] NVARCHAR(MAX) NOT NULL,
    [Title] NVARCHAR(MAX) NOT NULL DEFAULT '',
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [UploadedById] NVARCHAR(MAX) NOT NULL DEFAULT ''
);